version: 2.1

executors:
  python:
    working_directory: ~/dee
    docker:
      - image: python:3.7

commands:
  all:
    parameters:
      version:
        type: string

    steps:
      - checkout

      - run:
          name: Install pipenv
          command: pip install pipenv black

      - run:
          name: Install deps
          command: pipenv install --python << parameters.version >> --system --dev

      - run:
          name: Check for security vulnerabilities
          command: pipenv check

      - run:
          name: Check format
          command: black --diff --check .

      - run:
          name: Lint
          command: pipenv run flake8 .

jobs:
  python:
    parameters:
      version:
        type: string
    executor: python
    steps:
      - all:
          version: << parameters.version >>

workflows:
  stack:
    jobs:
      - python:
          version: "2.7"
      - python:
          version: "3.4"
      - python:
          version: "3.5"
      - python:
          version: "3.6"
      - python:
          version: "3.7"
