version: 2

jobs:
  build:
    working_directory: ~/dee

    docker:
      - image: python:3.6

    steps:
      - checkout

      - run:
          name: Install pipenv
          command: pip install pipenv black

      - run:
          name: Install deps
          command: pipenv install --system --dev

      - run:
          name: Check for security vulnerabilities
          command: pipenv check

      - run:
          name: Check format
          command: black --diff --check .

      - run:
          name: Lint
          command: flake8 .
