version: "2.1"

executors:
  py36:
    working_directory: ~/dee
    docker:
      - image: python:3.6
  py37:
    working_directory: ~/dee
    docker:
      - image: python:3.7

commands:
  stack:
    steps:
      - checkout

      - run:
          name: Install pipenv
          command: pip install pipenv black

      - run:
          name: Install deps
          command: pipenv install --system --dev

      - run:
          name: Check for security vulnerabilities
          command: pipenv check

      - run:
          name: Check format
          command: black --diff --check .

      - run:
          name: Lint
          command: flake8 .

jobs:
  py36:
    executor: py36
    steps: stack
  py37:
    executor: py37
    steps: stack

workflows:
  stack:
    jobs:
      - py36
      - py37
